### ISSUE TITLE
java 8 compatibility ?

### ISSUE THREAD

**Issue by Marthym** [efluid/testControlByteCode#8]
Do you plan to have a java 8 build ? 

The code is mainly compatible and lot of projects use it for now.

**Comment by tcollignon** [comment]
Hi @Marthym 

Yes I agree, we will do that.
Thx for your PR, I will take a look at this this week.

Do you still use testControlByteCode? If yes WDYT about it?

Thx

**Comment by Marthym** [comment]
Yes we plan to use it for similar reasons than yours.

I found the approch interresting and we would like to contribute to the project

**Comment by boutss** [comment]
It wasn't a strong will to update in 11.
Indeed it is more interesting to be the most compatible with a maximum of project. 
It's merged. Thanks again.

**Comment by boutss** [comment]
It is planned to translate the code in english soon. ^^

**Comment by tcollignon** [comment]
Thx @Marthym 

@boutss you can roll a new release 1.1.0 please?

**Comment by Marthym** [comment]
Cool

I-Run. will contribute soon with pull-request on junit 5

Thx
